winzou_state_machine:
    bitbag_sylius_smash_promoton_smash:
        class: "%bitbag_sylius_smash_promotion.model.smash.class%"
        property_path: state
        graph: bitbag_sylius_smash_promoton_smash
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            accepted: ~
            rejected: ~
        transitions:
            accept:
                from: [new]
                to: accepted
            reject:
                from: [new]
                to: rejected
        callbacks:
            before:
                bitbag_sylius_smash_promotion_resolve_promotion_coupon:
                    on: ["accept"]
                    do: ["@bitbag_sylius_smash_promotion.resolver.smash_promotion_coupon", "resolvePromotionCoupon"]
                    args: ["object"]
